var breakfast = [
    {foodName: 'Eggs Benedict', id: 1, price: '8.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/q0thK2Y/breakfast1.png', category: 'breakfast'},
    {foodName: 'Breakfast Sandwich', id: 2, price: '9.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/FzN5LrG/breakfast2.png', category: 'breakfast'},
    {foodName: 'Baked Chicken', id: 3, price: '10.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/G0FH09t/breakfast3.png', category: 'breakfast'},
    {foodName: 'Bagel and Cream Cheese', id: 4, price: '6.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/vPjHK53/breakfast4.png', category: 'breakfast'},
    {foodName: 'Full Breakfast Fried Egg Toast Brunch', id: 5, price: '3.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/BcfH6jt/breakfast5.png', category: 'breakfast'},
    {foodName: 'Toast Croissant Fried Egg', id: 6, price: '19.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/2k9Pj2B/breakfast6.png', category: 'breakfast'},
]

export default breakfast;