var dinner = [
    {foodName: 'Baked Chicken', id: 13, price: '9.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/pRK8Bp9/dinner1.png', category: 'dinner'},
    {foodName: 'Lemony Salmon Piccata', id: 14, price: '10.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/xSnDmB6/dinner2.png', category: 'dinner'},
    {foodName: 'Garlic Butter Baked Salmon', id: 15, price: '6.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/XVfZk6K/dinner3.png', category: 'dinner'},
    {foodName: 'French Fries with Cheese', id: 16, price: '8.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/FKXWzfr/dinner4.png', category: 'dinner'},
    {foodName: 'Pork Tenderloin with Quinoa Pilaf', id: 17, price: '12.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/wCQ6bXh/dinner5.png', category: 'dinner'},
    {foodName: 'Salmon with Grapefruit and Lentil Salad', id: 18, price: '9.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/5hLB7Ys/dinner6.png', category: 'dinner'}
]

export default dinner;