var lunch = [
    {foodName: 'Beef Steak', id: 7, price: '15.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/vQHd7jy/lunch1.png', category: 'lunch'},
    {foodName: 'Honey-Soy-Glazed Salmon with Peppers', id: 8, price: '7.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/pfq6mhg/lunch2.png', category: 'lunch'},
    {foodName: 'Tarragon-Rubbed-Salmon', id: 9, price: '6.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/6HxpVvD/lunch3.png', category: 'lunch'},
    {foodName: 'Indian Lunch', id: 10, price: '8.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/yq3rdmJ/lunch4.png', category: 'lunch'},
    {foodName: 'Fried Chicken Bento', id: 11, price: '9.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/t3H07Nz/lunch5.png', category: 'lunch'},
    {foodName: 'Healthy Meal Plan', id: 12, price: '23.99', detail: 'How we dream about our Future.', foodDetails: 'Gay one the what walt then she. Demesne mention promise you justice arrived way. Amazing foods are Or and increasing to in especially inquietude companions acceptance admiration. Outweigh it families distance wandered ye.', foodImage: 'https://i.ibb.co/h12F6f5/lunch6.png', category: 'lunch'},
]

export default lunch;